
"""
Module for screen capture, image filtering, and AI-based summarization of user actions.
Functions:
    screenshot(image_path: str = "./memory/images/screen") -> Image:
        Returns the resized PIL Image object and save it in a directory
    filter_pictures(image_dir: str = "./memory/images", threshold: int = 8) -> list:
        Returns a list of filenames for images that are sufficiently different from their predecessor.
    summarize_images(client: openai.OpenAI, images_paths_list: list) -> str:
        Returns a summary of user actions with timestamps, as generated by the AI model.
"""
#file/directory manipulation
import os
import shutil
import memory
#image manipulation
import mss
from PIL import Image
import imagehash
import base64
#date/time
import re
from datetime import datetime
#ai analisis
import openai


def screenshot(image_path :str = "./memory/images/screen") -> Image:
    try:
        os.makedirs("./memory/images")
    except:
        pass
    """
    Captures a screenshot of the primary monitor, resizes it to 1280x720 (720p), and saves it as a JPEG image with a timestamp in the filename.
    Args:
        image_path (str): The base path where the screenshot will be saved. Defaults to "./memory/images/screen".
    Returns:
        Image: The resized PIL Image object of the captured screenshot.
    Notes:
        - After the directory name in 'image_path' you need to write the name of the file. It will then add the time and the extention
        - If the target folder does not exist, the function will silently fail to save the image but still return the resized image.
        - The filename includes the current date and time with millisecond precision.
    """

    
    
    with mss.mss() as sct:
        # Capture the primary monitor
        monitor = sct.monitors[1]  # [1] is main screen
        screenshot = sct.grab(monitor)
        
        #gets the time of when the picture was taken
        now = datetime.now()
        date = now.strftime("%Y-%m-%d %Hh%M %Ss %fms")

        # Convert to PIL image
        img = Image.frombytes("RGB", screenshot.size, screenshot.rgb)

        # Resize/compress to 720p
        img_resized = img.resize((1280,720), Image.LANCZOS)

        # Save file. pass if folder does not exist
        try:
            img_resized.save(f"{image_path} {date}.jpg", quality=85)
        except:
            pass
        
        return img_resized
    
def filter_pictures(image_dir: str = "./memory/images",threshold : int = 8) -> list:
    """
    Filters images in a directory by perceptual hash similarity.
    Iterates through all images in the specified directory, computes their perceptual hash (phash),
    and selects images that are sufficiently different from the previous image based on a hash threshold.
    Args:
        image_dir (str): Path to the directory containing images. Defaults to "./memory/images".
        threshold (int): The minimum hash difference required to consider two images as different. Defaults to 8.
    Returns:
        list: A list of filenames for images that are sufficiently different from their predecessor.
    """
    
    filtered = []
    prev_hash = None
    
    def is_different(hash1, hash2, threshold=5):
        return abs(hash1 - hash2) > threshold

    for path in os.listdir(image_dir):
        h = imagehash.phash(Image.open(f"{image_dir}/{path}"))
        if prev_hash is None or is_different(prev_hash, h, threshold):
            filtered.append(path)
        prev_hash = h

    return filtered

def summarize_images(client: openai.OpenAI,images_paths_list: list,name: str) -> str:
    """
    Summarizes a sequence of screen images by sending them to the OpenAI API for analysis.
    Each image is encoded in base64 and sent along with its timestamp (extracted from the filename) 
    to the AI model, which generates a concise summary of user actions observed in the images, 
    formatted with timestamps. Images deemed not useful by the model are skipped in the summary.
    After processing, the images directory is cleared and recreated.
    Args:
        client (openai.OpenAI): An initialized OpenAI API client.
        images_paths_list (list): List of image filenames to be summarized.
    Returns:
        str: A summary of user actions with timestamps, as generated by the AI model.
    """
    
    time = None
    
    #instructions for ai model
    gpt_message = [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    #"text": "You are looking at a 30 sec stream of someones screen but it's cut in multiple images that represents the main changes, summarize in simples sentences what happened with moderate detail. Remember you need to add context because you are one itteration of multiple so put in '[context]:' everything that will be important because after your analysis you wiil loose memory so add everything you wish to remember inside like for exemple: 'what game he is currently playing, why did he stopped splaying, what is he working on, he switch from this game to this game. he quit playing 10min for work ago so his break had ended' ect..."
                    "text": "You are looking at a 30sec stream of someones screen, make a summary of what happened, don't add anything else just write a summary"
                },
            ]
            
        },
        {
            "role": "assistant",
            "content": [{"type": "text", "text": memory.get_memory("screenlogs",name)}]
        },
    ]
    
    nb = 0 #counter
    for image in images_paths_list:
        nb += 1
        with open(f"./memory/images/{image}", "rb") as f:
            img_b64 = base64.b64encode(f.read()).decode("utf-8") #encode images to b64 for openai
            match = re.search(r'(\d{4}-\d{2}-\d{2} \d{2}h\d{2} \d{2}s \d+ms)', image) #search the date in the image file name
        if match:
            time = match.group(1)
        # gpt_message[0]["content"].append( 
        #     {"type": "text", "text": f"image{nb} Taken at: {time}"}, #adds context with to the image with the order and time of when it was taken
        # )
        #adds the image for openai model to read
        gpt_message[0]["content"].append( 
            {
                
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}
            }
        )
        
    # deletes and remake the images folder to delete all his content
    def dir_is_empty(path):
        try:
            return not any(os.scandir(path))
        except FileNotFoundError:
            pass
    
    while dir_is_empty("./memory/images") == False:
        print("trying to remove ./memory/images")
        try:
            shutil.rmtree("./memory/images")
            print("dirrectory removed successfully")
        except:
            print("fail")
            continue
    os.makedirs("./memory/images")
    print("clean dirrectory created")
    
    # send request to summarize to openai api
    completion = client.chat.completions.create(
    model="gpt-4o-mini",
    messages = gpt_message,
    )
    
    text = completion.choices[0].message.content
    return "\n"+text